baseurl = "/"
languageCode = "en-us"
title = "R.bio-spring.info"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = "bio-spring-netlify-com"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"
    
[[menu.main]]
    name = "CV"
    url = "/cv/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub Repository"
    url = "https://github.com/gaospecial/bio-spring.info/"
[[menu.main]]
    name = "Wordpress blog"
    url = "http://bio-spring.info"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "r.bio-spring.info"

